AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Amplify and AppRunner projects within a monorepo.

Parameters:
  GitHubBaseURL:
    Description: The base URL of the GitHub repository, including the branch and folder paths.
    Type: String

  GitHubToken:
    Description: The GitHub OAuth token for accessing the repository.
    Type: String
    NoEcho: true

  ProjectName:
    Description: The name of the first Amplify project (e.g., amplify-chat-admin).
    Type: String

  SecondProjectName:
    Description: The name of the second Amplify project (e.g., amplify-chat-ui).
    Type: String

  Environment:
    Description: The environment (e.g., production, staging).
    Type: String

  JWTSecret:
    Description: The JWT secret to be used for authentication.
    Type: String

  KendraIndexId:
    Description: The ID of the Kendra Index.
    Type: String

  ChatProdApi:
    Description: The API endpoint for the chat production environment.
    Type: String

  BHASHINI_USER_ID:
    Description: Optional Bhashini User ID for integration.
    Type: String
    Default: ""

  BHASHINI_API_KEY:
    Description: Optional Bhashini API Key for integration.
    Type: String
    Default: ""

Resources:
  # Extract components from the GitHubBaseURL
  GitHubUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/GitHubUser"
      Type: String
      Value: !Select [3, !Split ["/", !Sub "${GitHubBaseURL}"]]

  GitHubRepo:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/GitHubRepo"
      Type: String
      Value: !Select [4, !Split ["/", !Sub "${GitHubBaseURL}"]]

  GitHubBranch:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/GitHubBranch"
      Type: String
      Value: !Select [5, !Split ["/", !Sub "${GitHubBaseURL}"]]

  AmplifyApp1:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref ProjectName
      Description: !Sub "Amplify project for ${ProjectName} in ${Environment} environment"
      OauthToken: !Ref GitHubToken
      Repository: !Sub "https://github.com/${GitHubUser}/${GitHubRepo}"
      BranchName: !Ref GitHubBranch
      EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: !Ref Environment
        - Name: JWT_SECRET
          Value: !Ref JWTSecret
        - Name: KENDRA_INDEXID
          Value: !Ref KendraIndexId
        - Name: CHAT_PROD_API
          Value: !Ref ChatProdApi
        - Name: BHASHINI_USER_ID
          Value: !Ref BHASHINI_USER_ID
        - Name: BHASHINI_API_KEY
          Value: !Ref BHASHINI_API_KEY
      SourceCodeUrl: !Sub "https://github.com/${GitHubUser}/${GitHubRepo}/tree/${GitHubBranch}/amplify-chat-admin"
      BuildSpec: |
        version: 1.0
        frontend:
          phases:
            preBuild:
              commands:
                - echo Installing dependencies...
                - npm install
            build:
              commands:
                - echo Building the project...
                - npm run build
          artifacts:
            baseDirectory: /build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AmplifyApp2:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref SecondProjectName
      Description: !Sub "Second Amplify project for ${SecondProjectName} in ${Environment} environment"
      OauthToken: !Ref GitHubToken
      Repository: !Sub "https://github.com/${GitHubUser}/${GitHubRepo}"
      BranchName: !Ref GitHubBranch
      EnvironmentVariables:
        - Name: ENVIRONMENT
          Value: !Ref Environment
        - Name: APPRUNNER_API_URL
          Value: !GetAtt AppRunnerService.ServiceUrl
      SourceCodeUrl: !Sub "https://github.com/${GitHubUser}/${GitHubRepo}/tree/${GitHubBranch}/amplify-chat-ui"
      BuildSpec: |
        version: 1.0
        frontend:
          phases:
            preBuild:
              commands:
                - echo Installing dependencies...
                - npm install
            build:
              commands:
                - echo Building the project...
                - npm run build
          artifacts:
            baseDirectory: /build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

Outputs:
  GitHubUser:
    Description: Extracted GitHub username from the base URL
    Value: !Ref GitHubUser

  GitHubRepo:
    Description: Extracted GitHub repository name from the base URL
    Value: !Ref GitHubRepo

  GitHubBranch:
    Description: Extracted GitHub branch name from the base URL
    Value: !Ref GitHubBranch

  AmplifyAppUrl1:
    Description: The URL of the Amplify App for the first project.
    Value: !Sub "https://${AmplifyApp1.DefaultDomain}"

  AmplifyAppUrl2:
    Description: The URL of the Amplify App for the second project.
    Value: !Sub "https://${AmplifyApp2.DefaultDomain}"
